[project]
dependencies = [
	"astropy",
	"dash",
	"numpy",
	"plotly-stubs", # pypi
	"plotly",
	"requests",
	"types-requests",
]
name = "SpecViewer"
requires-python = ">=3.10"

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[tool.pixi.tasks]
main = "python sdssv_spec_appREMOTE.py"
sync = "git pull -ptr && pixi install"
test = "pytest --rootdir util -v"

[tool.pixi.dependencies]
astropy = "<=4.3.1"
dash = "<=2.9.1"
numpy = "<=1.21.4"
plotly = "<=5.0.0"
pytest = "*"
python = "~=3.10.18"
requests = "<=2.23.0"
types-requests = "*"

# [tool.pixi.pypi-dependencies]
# plotly-stubs = "*"
